name: issue template
description: template for issues
body: |
  ---
  name: Custom issue template
  about: Describe this issue template's purpose here.
  title: 'Style meeting minutes'
  labels: 'style'
  assignees: 'Mitchell'
  
  ---
